"""NumCompute package public API."""

from .io import load_array, save_array, load_csv, save_csv
from .preprocessing import (
    StandardScaler,
    MinMaxScaler,
    SimpleImputer,
    OneHotEncoder,
)
from .sort_search import (
    bubble_sort,
    insertion_sort,
    selection_sort,
    merge_sort,
    quick_sort,
    linear_search,
    binary_search,
)
from .rank import rankdata, percentile_rank, top_k
from .stats import (
    mean,
    median,
    std,
    min,
    max,
    histogram,
    quantile,
    StreamingStats,
    StreamingHistogram,
    StreamingQuantile,
    update_stats,
)
from .metrics import (
    accuracy,
    precision,
    recall,
    f1,
    confusion_matrix,
    mse,
    roc_curve,
    auc,
    MetricTracker,
    StreamingAccuracy,
    StreamingPrecision,
    StreamingRecall,
    StreamingF1,
    StreamingConfusionMatrix,
    StreamingMSE,
    StreamingAUC,
)
from .optim import numerical_gradient, gradient_descent, stochastic_gradient_descent
from .pipeline import Pipeline, FeatureUnion
from .utils import set_random_seed, chunk_array, train_test_split, describe_array
from .tree import DecisionTreeClassifier
from .ensemble import EnsembleClassifier, BaggingClassifier, RandomForestClassifier
from .stream import StreamTrainer, iter_chunks
from .visualise import (
    plot_metric_over_time,
    compare_models,
    plot_predictions_vs_ground_truth,
    plot_confusion_matrix,
    plot_roc_curve,
    plot_streaming_metric,
    plot_memory_usage,
)
from .benchmarking import (
    benchmark_function,
    compare_functions,
    format_benchmark_table,
    vectorized_sum_of_squares,
    loop_sum_of_squares,
    vectorized_topk,
    loop_topk,
    vectorized_pairwise_distance,
    loop_pairwise_distance,
    benchmark_tree_vs_forest,
    benchmark_streaming_pipeline,
    benchmark_chunk_sizes,
)

__all__ = [
    "load_array",
    "save_array",
    "load_csv",
    "save_csv",
    "StandardScaler",
    "MinMaxScaler",
    "SimpleImputer",
    "OneHotEncoder",
    "bubble_sort",
    "insertion_sort",
    "selection_sort",
    "merge_sort",
    "quick_sort",
    "linear_search",
    "binary_search",
    "rankdata",
    "percentile_rank",
    "top_k",
    "mean",
    "median",
    "std",
    "min",
    "max",
    "histogram",
    "quantile",
    "StreamingStats",
    "StreamingHistogram",
    "StreamingQuantile",
    "update_stats",
    "accuracy",
    "precision",
    "recall",
    "f1",
    "confusion_matrix",
    "mse",
    "roc_curve",
    "auc",
    "MetricTracker",
    "StreamingAccuracy",
    "StreamingPrecision",
    "StreamingRecall",
    "StreamingF1",
    "StreamingConfusionMatrix",
    "StreamingMSE",
    "StreamingAUC",
    "numerical_gradient",
    "gradient_descent",
    "stochastic_gradient_descent",
    "Pipeline",
    "FeatureUnion",
    "set_random_seed",
    "chunk_array",
    "train_test_split",
    "describe_array",
    "DecisionTreeClassifier",
    "EnsembleClassifier",
    "BaggingClassifier",
    "RandomForestClassifier",
    "StreamTrainer",
    "iter_chunks",
    "plot_metric_over_time",
    "compare_models",
    "plot_predictions_vs_ground_truth",
    "plot_confusion_matrix",
    "plot_roc_curve",
    "plot_streaming_metric",
    "plot_memory_usage",
    "benchmark_function",
    "compare_functions",
    "format_benchmark_table",
    "vectorized_sum_of_squares",
    "loop_sum_of_squares",
    "vectorized_topk",
    "loop_topk",
    "vectorized_pairwise_distance",
    "loop_pairwise_distance",
    "benchmark_tree_vs_forest",
    "benchmark_streaming_pipeline",
    "benchmark_chunk_sizes",
]
